### ISSUE TITLE
Suggestions coming from WP support forum

### ISSUE THREAD

**Issue by amElnagdy** [amElnagdy/salt-shaker#12]
1) When saving the new salts, add \r\n to each salt line instead of just \n

2) You read and write the files for each salt. You should read once, and write once. I’d read in all lines into an array, illiterate through them for each salt, then save once.

3) MAJOR!! you are changing the permissions on the file to a read only file, after changing only the first salt. The remaining salts never get changed, nor can you change the salts the following week (day or month)

4) in core.class.php you get the name of the config file by checking if the file exists, ” ABSPATH . ‘wp-config.php’ “.. This file will ALWAYS exist, even if you move your wp-config.php to a non public folder, because the file still has to exist to use to include the “moved” file. There needs to be another way to do this, but I’m not sure how yet. Maybe define a constant in the original location for your wp-config, before doing the include?

**https://wordpress.org/support/topic/recomendations-for-plugin/

**Comment by sanbec** [comment]
Items 2 and 3 resolved with #23 (and his second commit)
