### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by jirsbek** [amElnagdy/salt-shaker#18]
I'm sorry for the brief and cheap title, but I'm trying hard to get the plugin working.

Long story short, I'm checking the wp-config.php on the server but nothing has changed. The wp-config.php has even CHMOD 777 set.

I'm using iThemes Security plugin, but salts in wp-config.php are not changed even when the plugin is disabled.

(Although on my localhost I see the change in the salts.)

**Comment by amElnagdy** [comment]
Hi @jirsbek 
It's OK about the title 😄 

First of all, you should not chmod your config file 777.

About the plugin is not working, it's hard to tell why according to your description but what I can tell, it's server related issue (as it works fine here and on your localhost).

When you deactivated iThemes plugin, have you deactivated and activated Salt Shaker again?

**Comment by jirsbek** [comment]
I think the same – it's maybe related to the server user trying to do the wp-config change.

Anyway yes, I tried deactivated and activated Salt Shaker as well as trying to activate the plugin on the WordPress site not using the security plugin (but on the same server).

iThemes security has an option to change the salts also, it only does that immediately without the option to set the schedule.
