### ISSUE TITLE
Option for configurations were salt keys are outside wp-config

### ISSUE THREAD

**Issue by ghost** [amElnagdy/salt-shaker#19]
First of all, great job. Your plugin is very useful. 

**Issue**
I installed your plugin and realized it wasn't working on my site. For additional security reason, I moved the salt keys outside of my wp-config file. As you can guess, that prevent your script from working.

**How I fixed it**
To fix my issue, I simply hardcoded the name of my file inside core.class.php in place of wp-config. Quick and easy fix.

**Suggestions**
It would be nice if advanced users could in the setting, select the PHP file that holds their salt keys.

What do you think?

**Comment by amElnagdy** [comment]
Thanks @oliviervp for the suggestion. Could you please let me know how can I reproduce this scenario? In other words, how can I move the keys outside the config file?

**Comment by amElnagdy** [comment]
In Salt Shaker 1.2.2, a filter is added to define the file name that contains the salts
For example, add this in your theme's functions.php
```
function salts_file(){
    return 'custom-config';  //write the file name without .php
}
add_filter( 'salt_shaker_salts_file', 'salts_file' );
```
