### ISSUE TITLE
Reporting security issues?

### ISSUE THREAD

**Issue by ghost** [amElnagdy/salt-shaker#5]
I just reported two security issues on this plugin, see #3 and #4. While they can be used to harm a website using this plugin, the risks are low due to the low active install count and that I'm providing patches. 

However, I found a more severe one, that I would like to disclose and submit a PR for. Where can I safely report it to the maintainers, rather than making a public PR / issue?

Edit: three reports are left, I'm waiting for an answer to send it. Without any response for 30 days, I'll make PR for each one of them and report the plugin to _WordPress_, due to the risks caused by these findings.

**Comment by amElnagdy** [comment]
Hi @nashe 
Thanks for your reports 👍 
You can send your report to (nagdy@wpcolt.com)
