### ISSUE TITLE
A weird pseudo-issue

### ISSUE THREAD

**Issue by stefanos82** [amElnagdy/salt-shaker#8]
Hey @AhmedTheGeek,

First of all, congrats for this beautiful piece of tool, I simply love it.

Now, as my ticket title says I have faced a very weird issue as soon as I run it for the first time.

I'm using Debian testing 64-bit and after I run "Change now", I went to double-check that it had indeed modified my `wp-config.php` file.

Well, it did but not the way I thought it would. It converted it to a Windows style file, that is by adding `^M` all over the entire file.

I run `dos2unix`, re-run it with "Change now" and works as expected.

I will clone the plugin and I will try to reproduce this rather peculiar behavior because it will drive me nuts.

Any suggestions before I attempt to do so?

Cheers.

**Comment by amElnagdy** [comment]
Hey Stef,
Thanks for stopping by. 

I'm not sure why this is happening. I'm away for a few days.
If you can test 1.1.3 and check if the same thing happens too. https://plugins.trac.wordpress.org/browser/salt-shaker/tags/1.1.3?rev=1666730

Maybe the latest changes caused something.

**Comment by stefanos82** [comment]
No worries mate, I will double-check everything and will let you know/

Enjoy your time.

Cheers.

**Comment by stefanos82** [comment]
![selection_001](https://user-images.githubusercontent.com/1777466/29380679-3e8782cc-82cf-11e7-89b6-27b357b9925a.png)

This had happened before and I thought it was my fault. As soon as the changes are applied, this popup message appears letting me know that my session has expired.

I will try your suggestion and diff the code to see the possible cause behind this problem.

**Comment by amElnagdy** [comment]
This is so expected ☺️
Changing salts keys forces everyone to login again.

**Comment by stefanos82** [comment]
Well, it should be mentioned as a note or a warning right before the button area.

**Comment by amElnagdy** [comment]
I already added a red warning at the top of the settings page. I'll move it ;)

**Comment by stefanos82** [comment]
Maybe a balloon notification would be a better suggestion when a user presses the button?

Something like "Please be warned that as soon as the changes take place you need to re-login to re-initiate your session".

Does it sound better to you this way?

**Comment by stefanos82** [comment]
Hahaha, I have just read your message. I didn't pay attention to it, because I thought it was a standard notification that letting users know there is a running process that modifies the file and should not be interrupted.

That message sounds cool, but it's not bold enough nor is it visible to be considered a sound message.

Just increase the font size and that will do mate.

**Comment by amElnagdy** [comment]
Nice suggestion. I'll move it a bit doen and increase the font size.

Thanks bud!

**Comment by stefanos82** [comment]
My pleasure mate. 

In the meantime, I'm investigating further this ghostly behavior. I have never seen something like that before.

**Comment by stefanos82** [comment]
I have found the problem thanks to `git diff --no-index salt-checker-1.1.3/ salt-checker-1.1.5/` command :sunglasses:

Your editor or your IDE (I presume Intellij IDE based on your .idea folder) uses `CRLF` characters which is `\r\n`, whereas on UNIX-like environment it just uses `LF` which is `\n`.

Can you check your preferences and set it accordingly? If not, check whether `trac` gives you the option to convert them to `LF`.

I know that [git gives you such option](https://help.github.com/articles/dealing-with-line-endings/).

**Comment by amElnagdy** [comment]
Very nice catch!
I'll look into it once i get back to work.

Thanks again!

**Comment by stefanos82** [comment]
My pleasure mate.

Should I close this ticket or will you do it after your confirm this issue?

**Comment by amElnagdy** [comment]
I'll do when i confirm and fix.
Cheers!

**Comment by amElnagdy** [comment]
Everything should be fine now 💯
